# Guided Capstone Step 4. Pre-Processing and Training Data Development

**The Data Science Method**  


1.   Problem Identification 


2.   Data Wrangling 
  
 
3.   Exploratory Data Analysis   

4.   **Pre-processing and Training Data Development**  
 * Create dummy or indicator features for categorical variables
  * Standardize the magnitude of numeric features
  * Split into testing and training datasets
  * Apply scaler to the testing set
5.   Modeling 
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

**<font color='teal'> Start by loading the necessary packages as we did in step 3 and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pickle
%matplotlib inline

In [2]:
path = os.getcwd()
print(path)

/home/joe/Desktop/GuidedCapstone/Step4_and_5

**<font color='teal'>  Load the csv file you created in step 3, remember it should be saved inside your data subfolder and print the first five rows.</font>**

In [3]:
df = pd.read_csv(path+'/../Step3/data/step3_output.csv')
df.head()

,Name,state,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,...,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,projectedDaysOpen,NightSkiing_ac,clusters
0,Hilltop Ski Area,Alaska,2090,294,0,0.0,0,0,0,1,...,1.0,30.0,30.000000,150.000000,36.0,69.0,30.000000,152.0,30.0,2
1,Sunrise Park Resort,Arizona,11100,1800,0,0.0,0,1,2,3,...,1.2,800.0,80.000000,115.000000,49.0,250.0,74.000000,104.0,80.0,1
2,Yosemite Ski & Snowboard Area,California,7800,600,0,0.0,0,0,0,1,...,0.4,88.0,174.873239,110.000000,84.0,300.0,47.000000,107.0,0.0,1
3,Donner Ski Ranch,California,8012,750,0,0.0,0,0,0,1,...,1.5,505.0,60.000000,163.000000,82.0,400.0,75.000000,170.0,0.0,1
4,June Mountain,California,10090,2590,0,0.0,0,2,0,0,...,2.0,1500.0,174.873239,115.103943,58.0,250.0,57.916957,128.0,0.0,1

In [4]:
df.describe()

,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,double,surface,...,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,projectedDaysOpen,NightSkiing_ac,clusters
count,168.000000,168.000000,168.0,168.0,168.0,168.000000,168.000000,168.000000,168.000000,168.000000,...,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000
mean,3622.982143,844.529762,0.0,0.0,0.0,0.238095,0.547619,1.154762,1.648810,2.226190,...,0.996229,259.516674,105.185027,105.756656,59.295575,146.094635,50.033804,111.769792,44.958333,1.446429
std,3235.918035,593.487278,0.0,0.0,0.0,0.601775,0.716023,1.228348,1.376187,1.417184,...,0.742963,385.654378,78.183817,21.921813,14.321377,105.253364,15.966336,20.818631,61.337132,0.748323
min,315.000000,175.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,15.000000,13.000000,56.000000,22.000000,18.000000,20.000000,56.000000,0.000000,0.000000
25%,1245.000000,361.250000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,...,0.400000,50.000000,44.250000,93.500000,51.000000,54.250000,39.000000,100.000000,0.000000,1.000000
50%,2000.000000,650.000000,0.0,0.0,0.0,0.000000,0.000000,1.000000,1.000000,2.000000,...,1.000000,115.000000,84.000000,110.000000,58.000000,120.000000,49.000000,115.000000,35.000000,2.000000
75%,6016.750000,1150.000000,0.0,0.0,0.0,0.000000,1.000000,2.000000,2.000000,3.000000,...,1.449923,251.250000,174.873239,115.103943,68.250000,210.000000,57.916957,120.289753,70.000000,2.000000
max,12075.000000,2600.000000,0.0,0.0,0.0,3.000000,2.000000,6.000000,6.000000,6.000000,...,4.000000,3000.000000,600.000000,163.000000,95.000000,500.000000,89.000000,180.000000,600.000000,2.000000

In [5]:
#removing useless columns with all 0 values
df.drop(['trams','fastEight','fastSixes'], axis=1, inplace=True)

In [6]:
df.describe()

,summit_elev,vertical_drop,fastQuads,quad,triple,double,surface,total_chairs,Runs,TerrainParks,LongestRun_mi,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,projectedDaysOpen,NightSkiing_ac,clusters
count,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000
mean,3622.982143,844.529762,0.238095,0.547619,1.154762,1.648810,2.226190,5.815476,29.785714,2.133598,0.996229,259.516674,105.185027,105.756656,59.295575,146.094635,50.033804,111.769792,44.958333,1.446429
std,3235.918035,593.487278,0.601775,0.716023,1.228348,1.376187,1.417184,2.558630,18.066458,0.950531,0.742963,385.654378,78.183817,21.921813,14.321377,105.253364,15.966336,20.818631,61.337132,0.748323
min,315.000000,175.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,0.000000,15.000000,13.000000,56.000000,22.000000,18.000000,20.000000,56.000000,0.000000,0.000000
25%,1245.000000,361.250000,0.000000,0.000000,0.000000,1.000000,1.000000,4.000000,15.750000,1.000000,0.400000,50.000000,44.250000,93.500000,51.000000,54.250000,39.000000,100.000000,0.000000,1.000000
50%,2000.000000,650.000000,0.000000,0.000000,1.000000,1.000000,2.000000,5.000000,24.000000,2.000000,1.000000,115.000000,84.000000,110.000000,58.000000,120.000000,49.000000,115.000000,35.000000,2.000000
75%,6016.750000,1150.000000,0.000000,1.000000,2.000000,2.000000,3.000000,7.000000,42.000000,2.820789,1.449923,251.250000,174.873239,115.103943,68.250000,210.000000,57.916957,120.289753,70.000000,2.000000
max,12075.000000,2600.000000,3.000000,2.000000,6.000000,6.000000,6.000000,14.000000,105.000000,4.000000,4.000000,3000.000000,600.000000,163.000000,95.000000,500.000000,89.000000,180.000000,600.000000,2.000000

## Create dummy features for categorical variables

**<font color='teal'> Create dummy variables for `state`. Add the dummies back to the dataframe and remove the original column for `state`. </font>**

Hint: you can see an example of how to execute this in Aiden's article on preprocessing [here](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-pre-processing-and-training-data-development-fd2d75182967).

In [7]:
df = pd.concat([df.drop('state', axis=1), pd.get_dummies(df.state)], axis=1)

In [8]:
df.head()

,Name,summit_elev,vertical_drop,fastQuads,quad,triple,double,surface,total_chairs,Runs,...,Rhode Island,South Dakota,Tennessee,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Hilltop Ski Area,2090,294,0,0,1,0,2,3,13.0,...,0,0,0,0,0,0,0,0,0,0
1,Sunrise Park Resort,11100,1800,1,2,3,1,0,7,65.0,...,0,0,0,0,0,0,0,0,0,0
2,Yosemite Ski & Snowboard Area,7800,600,0,0,1,3,1,5,10.0,...,0,0,0,0,0,0,0,0,0,0
3,Donner Ski Ranch,8012,750,0,0,1,5,2,8,52.0,...,0,0,0,0,0,0,0,0,0,0
4,June Mountain,10090,2590,2,0,0,4,1,7,41.0,...,0,0,0,0,0,0,0,0,0,0

## Standardize the magnitude of numeric features

**<font color='teal'> Using sklearn preprocessing standardize the scale of the features of the dataframe except the name of the resort which we done't need in the dataframe for modeling, so it can be droppped here as well. Also, we want to hold out our response variable(s) so we can have their true values available for model performance review. Let's set `AdultWeekend` to the y variable as our response for scaling and modeling. Later we will go back and consider the `AdultWeekday`, `dayOpenLastYear`, and `projectedDaysOpen`. For now leave them in the development dataframe. </font>**

In [9]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,158,159,160,161,162,163,164,165,166,167
Name,Hilltop Ski Area,Sunrise Park Resort,Yosemite Ski & Snowboard Area,Donner Ski Ranch,June Mountain,Mt. Shasta Ski Park,Mountain High,Ski China Peak,Soda Springs,Tahoe Donner,...,Nordic Mountain,Sunburst,Trollhaugen,Whitecap Mountain,Hogadon Basin,Sleeping Giant Ski Resort,Snow King Resort,Snowy Range Ski & Recreation Area,White Pine Ski Area,Big Mountain Resort
summit_elev,2090,11100,7800,8012,10090,6890,8200,8709,7352,7350,...,1137,1100,1200,1750,8000,7428,7808,9663,9500,6817
vertical_drop,294,1800,600,750,2590,1435,1600,1679,652,600,...,265,214,260,400,640,810,1571,990,1100,2353
fastQuads,0,1,0,0,2,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,3
quad,0,2,0,0,0,0,2,1,0,1,...,0,0,2,1,0,0,1,0,0,2
triple,1,3,1,1,0,3,2,4,1,1,...,1,0,0,0,0,1,1,1,2,6
double,0,1,3,5,4,0,5,2,1,0,...,1,3,1,4,1,1,1,3,0,0
surface,2,0,1,2,1,1,3,4,2,3,...,5,6,5,0,1,1,0,1,0,3
total_chairs,3,7,5,8,7,4,14,11,4,5,...,7,9,8,5,2,3,3,5,2,14
Runs,13,65,10,52,41,32,59,45,18,14,...,18,13,24,43,28,48,32,33,25,105
TerrainParks,1,2,2,2,2,2,1,1,2.82079,2,...,4,4,4,1,1,1,2,2,2.82079,4
LongestRun_mi,1,1.2,0.4,1.5,2,1.1,1.6,2.2,0.4,1,...,1,0.5,0.5,1,0.6,1,1,0.7,0.4,3.3
SkiableTerrain_ac,30,800,88,505,1500,425,290,1400,200,120,...,60,37,86,400,92,184,400,75,370,3000
Snow Making_ac,30,80,174.873,60,174.873,225,275,150,20,174.873,...,60,37,86,300,32,18,250,30,174.873,600
daysOpenLastYear,150,115,110,163,115.104,140,118,140,150,150,...,68,99,130,105,121,61,121,131,115.104,123
yearsOpen,36,49,84,82,58,34,95,62,83,48,...,43,59,69,57,61,81,80,59,81,72
averageSnowfall,69,250,300,400,250,300,108,300,400,400,...,80,50,50,200,80,310,300,250,150,333
AdultWeekday,30,74,47,75,57.917,49,84,83,50,69,...,57.917,33,54,60,48,42,59,49,57.917,81
projectedDaysOpen,152,104,107,170,128,130,150,144,144,144,...,90,115,120,118,95,77,123,120.053,120.053,123
NightSkiing_ac,30,80,0,0,0,0,73,0,0,0,...,60,37,86,0,0,0,110,0,0,600
clusters,2,1,1,1,1,1,1,1,1,1,...,2,2,2,2,1,1,1,1,1,1
Alaska,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Arizona,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
California,0,0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
Colorado,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Connecticut,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Idaho,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Illinois,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Indiana,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Iowa,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Maine,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Maryland,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Massachusetts,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Michigan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Minnesota,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Missouri,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Montana,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
Nevada,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
New Hampshire,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
New Jersey,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
New Mexico,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
New York,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
North Carolina,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ohio,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Oregon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pennsylvania,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Rhode Island,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
South Dakota,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tennessee,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Utah,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Vermont,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Virginia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Washington,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
West Virginia,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Wisconsin,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,0,0,0,0,0,0
Wyoming,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,0

In [10]:
# first we import the preprocessing package from the sklearn library
from sklearn import preprocessing

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X = df.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler()
scaler.fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X)

KeyError: "['AdultWeekend'] not found in axis"

## Split into training and testing datasets

**<font color='teal'> Using sklearn model selection import train_test_split, and create a 75/25 split with the y = `AdultWeekend`. We will start by using the adult weekend ticket price as our response variable for modeling.</font>**

In [ ]:
# Import the train_test_split function from the sklearn.model_selection utility.  
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

Here we start the actual modeling work. First let's fit a multiple linear regression model to predict the `AdultWeekend` price.

# Guided Capstone Step 5. Modeling

This is the fifth step in the Data Science Method. In the previous steps you cleaned and prepared the datasets. Now it's time to get into the most exciting part: modeling! In this exercise, you'll build three different models and compare each model's performance. In the end, you'll choose the best model for demonstrating insights to Big Mountain management.



### **The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.   **Modeling**
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

## Fit Models with a Training Dataset

**<font color='teal'> Using sklearn, fit the model on your training dataset.</font>**

#### Model 1

In [ ]:
#all first model set
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
lm = linear_model.LinearRegression()
model1 = lm.fit(X_train,y_train)

**<font color='teal'> Predict on the testing dataset and score the model performance with the y_test set and the y-pred values. The explained variance is a measure of the variation explained by the model. This is also known as the R-squared value. </font>**

Hint: you will have to use the `predict()` method here as it's used in this [DSM article](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-modeling-56b4233cad1b) about modeling.

In [ ]:
# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred = model1.predict(X_test)

## Review Model Outcomes — Iterate over additional models as needed

In [ ]:
# You might want to use the explained_variance_score() and mean_absolute_error() metrics.
# To do so, you will need to import them from sklearn.metrics. 
# You can plug y_test and y_pred into the functions to evaluate the model
from sklearn.metrics import explained_variance_score, mean_absolute_error

In [ ]:
print('explained variance: ' + str(explained_variance_score(y_test, y_pred)))
print('mean absolute error: ' + str(mean_absolute_error(y_test, y_pred)))

**<font color='teal'> Print the intercept value from the linear model. </font>**

Hint: our linear regression model `lm` has an attribute `intercept_` for the intercept

In [ ]:
print(lm.intercept_)
'''some of the coefficients in my regression (including this intercept) ended up unreasonably large.
All X-values were standardized to a z-value and y values were between 0 and 100 so I don't know why
coefficients as large as 10^11 showed up. I'm going to continue through the rest of the project
rather than spend too much time trying to debug/understand why this happened at this point in time.
'''

In [ ]:
print(y_pred)

In [ ]:
print(y_test)

In [ ]:
pd.DataFrame(y_pred).describe()
#y_pred values are large because they're computed from my regression's coefficients which are large

In [ ]:
X_with_coefs = pd.DataFrame(X_scaled.copy())
X_with_coefs.loc['coefs']=model1.coef_
X_with_coefs
#a little debugging to see what went wrong. Not all coefficients are large, but many are.

**<font color='teal'> The intercept is the mean `AdultWeekend` price for all the resorts given the other characteristics. The addition or subtraction of each of the coefficient values in the regression are numeric adjustments applied to the intercept to provide a particular observation's value for the resulting `AdultWeekend` value. Also, because we took the time to scale our x values in the training data, we can compare each of the coefficients for the features to determine the feature importances. Print the coefficient values from the linear model and sort in descending order to identify the top ten most important features.</font>** 


Hint: make sure to review the absolute value of the coefficients, because the adjustment may be positive or negative, but what we are looking for is the magnitude of impact on our response variable.

In [ ]:
# You might want to make a pandas DataFrame displaying the coefficients for each state like so: 
pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient']).sort_values(by='Coefficient', ascending=False)

**<font color='teal'>You should see that the top ten important features are different states. However, the state is not something the managers at the Big Mountain Resort can do anything about. Given that we care more about actionable traits associated with ticket pricing, rebuild the model without the state features and compare the results. </font>**

Hint: Try to construct another model using exactly the steps we followed above.

#### Model 2

In [ ]:
#dropping all columns with state info
df_no_state = df.iloc[:,0:22]

In [ ]:
df_no_state.head()

In [ ]:
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X = df_no_state.drop(['Name','AdultWeekend'], axis=1)
# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler()
scaler.fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X)

In [ ]:
# Import the train_test_split function from the sklearn.model_selection utility.  
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

In [ ]:
lm = linear_model.LinearRegression()
model2 = lm.fit(X_train,y_train)
y_pred = model2.predict(X_test)

In [ ]:
print('explained variance: ' + str(explained_variance_score(y_test, y_pred)))
print('mean absolute error: ' + str(mean_absolute_error(y_test, y_pred)))
print('y-intercept: '+str(lm.intercept_))

In [ ]:
pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient']).sort_values(by='Coefficient', ascending=False)

**<font color='teal'> When reviewing our new model coefficients, we see `summit_elev` is now in the number two spot. This is also difficult to change from a management prespective and highly correlated with `base_elev` and `vertical_drop`.  This time, rebuild the model without the state features and without the `summit_elev` and without `base_elev`and compare the results. </font>**

#### Model 3

In [ ]:
#I don't have base_elev feature, so only dropping summit_elev
df_no_state_elev = df_no_state.drop(axis=1, labels=['summit_elev'])

In [ ]:
# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X = df_no_state_elev.drop(['Name','AdultWeekend'], axis=1)
# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler()
scaler.fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X)

In [ ]:
# Import the train_test_split function from the sklearn.model_selection utility.  
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

In [ ]:
lm = linear_model.LinearRegression()
model3 = lm.fit(X_train,y_train)
y_pred = model3.predict(X_test)

In [ ]:
print('explained variance: ' + str(explained_variance_score(y_test, y_pred)))
print('mean absolute error: ' + str(mean_absolute_error(y_test, y_pred)))
print('y-intercept: '+str(lm.intercept_))

In [ ]:
pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient']).sort_values(by='Coefficient', ascending=False)

## Identify the Final Model

**<font color='teal'> Review the model performances in the table below and choose the best model for proving insights to Big Mountain management about what features are driving ski resort lift ticket prices. Type your choice in the final markdown cell — you will discuss this selection more in the next step of the guided casptone. </font>**

| Model | Explained Variance| Mean Absolute Error|Features Dropped|
| --- | --- | --- | --- |
| Model 1. | -3.4871197191798737e+23 | 2142520422208.8645 |-|
| Model 2. | 0.5559565165902216|6.852990686240759 |'state'|
| Model 3. | 0.5413080297878097 |7.275361831392762 |'state','summit_elev','base_elev'|

Model Selection:

I will choose Model 2. Model 2 looks to be the best predictor as it has the lowest mean absolute error.

In [ ]:
#legacy code that I probably won't need anymore. Use this if I need to save the model info in a  pkl file
'''
Pkl_Filename = "models/Model_2.pkl"
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(model2, file)

Pkl_Filename = "models/scaler.pkl"
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(scaler, file)'''