# Guided Capstone Step 4. Pre-Processing and Training Data Development

**The Data Science Method**  


1.   Problem Identification 


2.   Data Wrangling 
  
 
3.   Exploratory Data Analysis   

4.   **Pre-processing and Training Data Development**  
 * Create dummy or indicator features for categorical variables
  * Standardize the magnitude of numeric features
  * Split into testing and training datasets
  * Apply scaler to the testing set
5.   Modeling 
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

**<font color='teal'> Start by loading the necessary packages as we did in step 3 and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
path = os.getcwd()
print(path)

/home/joe/Desktop/GuidedCapstone/Step4_and_5

**<font color='teal'>  Load the csv file you created in step 3, remember it should be saved inside your data subfolder and print the first five rows.</font>**

In [3]:
df = pd.read_csv(path+'/../Step3/data/step3_output.csv')
df.head()

,Name,state,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,...,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
0,Hilltop Ski Area,Alaska,2090,294,0,0.0,0,0,0,1,...,30.0,30.000000,150.000000,36.0,69.0,30.000000,34.00000,152.0,30.0,1
1,Sunrise Park Resort,Arizona,11100,1800,0,0.0,0,1,2,3,...,800.0,80.000000,115.000000,49.0,250.0,74.000000,78.00000,104.0,80.0,0
2,Yosemite Ski & Snowboard Area,California,7800,600,0,0.0,0,0,0,1,...,88.0,174.873239,110.000000,84.0,300.0,47.000000,47.00000,107.0,0.0,0
3,Donner Ski Ranch,California,8012,750,0,0.0,0,0,0,1,...,505.0,60.000000,163.000000,82.0,400.0,75.000000,75.00000,170.0,0.0,0
4,June Mountain,California,10090,2590,0,0.0,0,2,0,0,...,1500.0,174.873239,115.103943,58.0,250.0,57.916957,64.16681,128.0,0.0,0

In [4]:
df.describe()

,summit_elev,vertical_drop,trams,fastEight,fastSixes,fastQuads,quad,triple,double,surface,...,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
count,167.000000,167.000000,167.0,167.0,167.0,167.000000,167.000000,167.000000,167.000000,167.000000,...,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000
mean,3603.856287,835.497006,0.0,0.0,0.0,0.221557,0.538922,1.125749,1.658683,2.221557,...,243.106594,102.222063,105.653403,59.219500,144.975442,49.848378,56.406439,111.702545,41.634731,0.916168
std,3236.111943,583.574495,0.0,0.0,0.0,0.563992,0.709221,1.172885,1.374345,1.420170,...,322.663730,68.306294,21.946731,14.330361,104.562439,15.831880,15.305689,20.862934,43.794339,0.624916
min,315.000000,175.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,15.000000,13.000000,56.000000,22.000000,18.000000,20.000000,20.000000,56.000000,0.000000,0.000000
25%,1240.000000,357.500000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.000000,1.000000,...,50.000000,43.500000,93.000000,51.000000,53.500000,39.000000,45.000000,100.000000,0.000000,1.000000
50%,2000.000000,650.000000,0.0,0.0,0.0,0.000000,0.000000,1.000000,1.000000,2.000000,...,115.000000,84.000000,110.000000,58.000000,120.000000,49.000000,55.000000,115.000000,35.000000,1.000000
75%,5779.500000,1150.000000,0.0,0.0,0.0,0.000000,1.000000,2.000000,2.000000,3.000000,...,245.000000,174.873239,115.103943,67.500000,207.000000,57.916957,65.000000,120.053004,69.500000,1.000000
max,12075.000000,2600.000000,0.0,0.0,0.0,2.000000,2.000000,5.000000,6.000000,6.000000,...,1704.000000,300.000000,163.000000,95.000000,500.000000,89.000000,93.000000,180.000000,180.000000,2.000000

In [5]:
df.drop(['trams','fastEight','fastSixes'], axis=1, inplace=True)

In [6]:
df.describe()

,summit_elev,vertical_drop,fastQuads,quad,triple,double,surface,total_chairs,Runs,TerrainParks,...,SkiableTerrain_ac,Snow Making_ac,daysOpenLastYear,yearsOpen,averageSnowfall,AdultWeekday,AdultWeekend,projectedDaysOpen,NightSkiing_ac,clusters
count,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,...,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000
mean,3603.856287,835.497006,0.221557,0.538922,1.125749,1.658683,2.221557,5.766467,29.335329,2.122422,...,243.106594,102.222063,105.653403,59.219500,144.975442,49.848378,56.406439,111.702545,41.634731,0.916168
std,3236.111943,583.574495,0.563992,0.709221,1.172885,1.374345,1.420170,2.485975,17.148751,0.942253,...,322.663730,68.306294,21.946731,14.330361,104.562439,15.831880,15.305689,20.862934,43.794339,0.624916
min,315.000000,175.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,...,15.000000,13.000000,56.000000,22.000000,18.000000,20.000000,20.000000,56.000000,0.000000,0.000000
25%,1240.000000,357.500000,0.000000,0.000000,0.000000,1.000000,1.000000,4.000000,15.500000,1.000000,...,50.000000,43.500000,93.000000,51.000000,53.500000,39.000000,45.000000,100.000000,0.000000,1.000000
50%,2000.000000,650.000000,0.000000,0.000000,1.000000,1.000000,2.000000,5.000000,24.000000,2.000000,...,115.000000,84.000000,110.000000,58.000000,120.000000,49.000000,55.000000,115.000000,35.000000,1.000000
75%,5779.500000,1150.000000,0.000000,1.000000,2.000000,2.000000,3.000000,7.000000,41.500000,2.820789,...,245.000000,174.873239,115.103943,67.500000,207.000000,57.916957,65.000000,120.053004,69.500000,1.000000
max,12075.000000,2600.000000,2.000000,2.000000,5.000000,6.000000,6.000000,14.000000,83.000000,4.000000,...,1704.000000,300.000000,163.000000,95.000000,500.000000,89.000000,93.000000,180.000000,180.000000,2.000000

## Create dummy features for categorical variables

**<font color='teal'> Create dummy variables for `state`. Add the dummies back to the dataframe and remove the original column for `state`. </font>**

Hint: you can see an example of how to execute this in Aiden's article on preprocessing [here](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-pre-processing-and-training-data-development-fd2d75182967).

In [7]:
df = pd.concat([df.drop('state', axis=1), pd.get_dummies(df.state)], axis=1)

In [8]:
df.head()

,Name,summit_elev,vertical_drop,fastQuads,quad,triple,double,surface,total_chairs,Runs,...,Rhode Island,South Dakota,Tennessee,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,Hilltop Ski Area,2090,294,0,0,1,0,2,3,13.0,...,0,0,0,0,0,0,0,0,0,0
1,Sunrise Park Resort,11100,1800,1,2,3,1,0,7,65.0,...,0,0,0,0,0,0,0,0,0,0
2,Yosemite Ski & Snowboard Area,7800,600,0,0,1,3,1,5,10.0,...,0,0,0,0,0,0,0,0,0,0
3,Donner Ski Ranch,8012,750,0,0,1,5,2,8,52.0,...,0,0,0,0,0,0,0,0,0,0
4,June Mountain,10090,2590,2,0,0,4,1,7,41.0,...,0,0,0,0,0,0,0,0,0,0

## Standardize the magnitude of numeric features

**<font color='teal'> Using sklearn preprocessing standardize the scale of the features of the dataframe except the name of the resort which we done't need in the dataframe for modeling, so it can be droppped here as well. Also, we want to hold out our response variable(s) so we can have their true values available for model performance review. Let's set `AdultWeekend` to the y variable as our response for scaling and modeling. Later we will go back and consider the `AdultWeekday`, `dayOpenLastYear`, and `projectedDaysOpen`. For now leave them in the development dataframe. </font>**

In [9]:
# first we import the preprocessing package from the sklearn library
from sklearn import preprocessing

# Declare an explanatory variable, called X,and assign it the result of dropping 'Name' and 'AdultWeekend' from the df
X = df.drop(['Name','AdultWeekend'], axis=1)

# Declare a response variable, called y, and assign it the AdultWeekend column of the df 
y = df.AdultWeekend

# Here we use the StandardScaler() method of the preprocessing package, and then call the fit() method with parameter X 
scaler = preprocessing.StandardScaler()
scaler.fit(X)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled=scaler.transform(X)

In [27]:
scaler.var_

array([1.04097114e+07, 3.38519915e+05, 3.16182007e-01, 4.99982072e-01,
       1.36742085e+00, 1.87751443e+00, 2.00480476e+00, 6.14306716e+00,
       2.92318692e+02, 8.82524922e-01, 5.20023036e-01, 1.03488458e+05,
       4.63781121e+03, 4.78774799e+02, 2.04129564e+02, 1.08678347e+04,
       2.49147547e+02, 4.32655662e+02, 1.90645939e+03, 3.88181720e-01,
       5.95216752e-03, 5.95216752e-03, 4.56093800e-02, 2.90437090e-02,
       2.90437090e-02, 3.46373122e-02, 1.76413640e-02, 1.18326222e-02,
       1.76413640e-02, 2.90437090e-02, 5.95216752e-03, 2.33783929e-02,
       8.17526623e-02, 4.56093800e-02, 1.18326222e-02, 1.76413640e-02,
       5.95216752e-03, 6.15296353e-02, 5.95216752e-03, 3.46373122e-02,
       1.00828284e-01, 1.76413640e-02, 2.33783929e-02, 1.76413640e-02,
       5.62945964e-02, 5.95216752e-03, 5.95216752e-03, 5.95216752e-03,
       1.76413640e-02, 4.01592026e-02, 1.18326222e-02, 2.33783929e-02,
       1.76413640e-02, 5.62945964e-02, 2.90437090e-02])

## Split into training and testing datasets

**<font color='teal'> Using sklearn model selection import train_test_split, and create a 75/25 split with the y = `AdultWeekend`. We will start by using the adult weekend ticket price as our response variable for modeling.</font>**

In [10]:
# Import the train_test_split function from the sklearn.model_selection utility.  
from sklearn.model_selection import train_test_split

# Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = y.ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

In [11]:
pd.DataFrame(y).describe()

                0
count  167.000000
mean    56.406439
std     15.305689
min     20.000000
25%     45.000000
50%     55.000000
75%     65.000000
max     93.000000

Here we start the actual modeling work. First let's fit a multiple linear regression model to predict the `AdultWeekend` price.

# Guided Capstone Step 5. Modeling

This is the fifth step in the Data Science Method. In the previous steps you cleaned and prepared the datasets. Now it's time to get into the most exciting part: modeling! In this exercise, you'll build three different models and compare each model's performance. In the end, you'll choose the best model for demonstrating insights to Big Mountain management.



### **The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.   **Modeling**
  * Fit Models with Training Data Set
  * Review Model Outcomes — Iterate over additional models as needed.
  * Identify the Final Model

6.   Documentation
  * Review the Results
  * Present and share your findings - storytelling
  * Finalize Code 
  * Finalize Documentation

## Fit Models with a Training Dataset

**<font color='teal'> Using sklearn, fit the model on your training dataset.</font>**

#### Model 1

In [12]:
#all first model set
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)

**<font color='teal'> Predict on the testing dataset and score the model performance with the y_test set and the y-pred values. The explained variance is a measure of the variation explained by the model. This is also known as the R-squared value. </font>**

Hint: you will have to use the `predict()` method here as it's used in this [DSM article](https://medium.com/@aiden.dataminer/the-data-science-method-dsm-modeling-56b4233cad1b) about modeling.

In [13]:
# Make a variable called y_pred and assign it the result of calling predict() on our model variable with parameter X_test
y_pred = model.predict(X_test)

## Review Model Outcomes — Iterate over additional models as needed

In [14]:
# You might want to use the explained_variance_score() and mean_absolute_error() metrics.
# To do so, you will need to import them from sklearn.metrics. 
# You can plug y_test and y_pred into the functions to evaluate the model
from sklearn.metrics import explained_variance_score, mean_absolute_error

In [15]:
print('explained variance: ' + str(explained_variance_score(y_test, y_pred)))
print('mean absolute error: ' + str(mean_absolute_error(y_test, y_pred)))

explained variance: -6.1088502041064874e+22
mean absolute error: 896749777640.2365

**<font color='teal'> Print the intercept value from the linear model. </font>**

Hint: our linear regression model `lm` has an attribute `intercept_` for the intercept

In [16]:
print(lm.intercept_)

225529884251.902

In [17]:
print(y_pred)

[5.10816956e+01 5.08512268e+01 5.14566956e+01 6.41793518e+01
 5.70650940e+01 6.76927795e+01 5.49293518e+01 4.14772034e+01
 4.04020081e+01 6.78219299e+01 5.58004456e+01 4.53981018e+01
 3.51598206e+01 5.11651917e+01 4.63180237e+01 6.03199768e+01
 4.03805237e+01 6.87066956e+01 7.34488831e+01 1.25552500e+13
 5.73141174e+01 4.44137268e+01 1.25529835e+13 1.25552572e+13
 6.29674377e+01 6.00738831e+01 5.64381409e+01 4.77731018e+01
 6.83658752e+01 6.79342346e+01 3.16402893e+01 5.73976135e+01
 6.57464905e+01 7.11637268e+01 6.16056213e+01 3.91146545e+01
 7.24850159e+01 3.27027893e+01 5.38629456e+01 8.03766174e+01
 5.56285706e+01 4.06344299e+01]

In [18]:
print(y_test)

[47.         49.         68.         59.         59.         71.
 58.         55.         54.         65.         62.         48.
 42.         42.         44.         65.         39.         69.
 79.         64.16681004 55.         45.         79.         64.16681004
 64.         45.         59.         47.         75.         60.
 39.         45.         68.         64.16681004 57.         40.
 72.         34.         35.         92.         59.         46.        ]

In [19]:
pd.DataFrame(y_pred).describe()

                  0
count  4.200000e+01
mean   8.967498e+11
std    3.272470e+12
min    3.164029e+01
25%    4.668179e+01
50%    5.675162e+01
75%    6.778964e+01
max    1.255526e+13

In [41]:
X_with_coefs = pd.DataFrame(X_scaled.copy())
X_with_coefs.loc['coefs']=model.coef_
X_with_coefs

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,-0.469208,-0.930688,-3.940186e-01,-7.621647e-01,-1.075355e-01,-1.210519e+00,-1.564765e-01,-1.116176e+00,-0.955432,-1.194793,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,-1.756821e-01
1,2.323371,1.657721,1.384390e+00,2.066313e+00,1.602791e+00,-4.807116e-01,-1.568994e+00,4.976891e-01,2.085979,-0.130315,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,-1.756821e-01
2,1.300562,-0.404756,-3.940186e-01,-7.621647e-01,-1.075355e-01,9.789036e-01,-8.627355e-01,-3.092437e-01,-1.130898,-0.130315,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,-1.756821e-01
3,1.366270,-0.146946,-3.940186e-01,-7.621647e-01,-1.075355e-01,2.438519e+00,-1.564765e-01,9.011555e-01,1.325626,-0.130315,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,-1.756821e-01
4,2.010329,3.015519,3.162798e+00,-7.621647e-01,-9.626985e-01,1.708711e+00,-8.627355e-01,4.976891e-01,0.682251,-0.130315,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,-1.756821e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,1.185263,-0.043822,-3.940186e-01,-7.621647e-01,-1.075355e-01,-4.807116e-01,-8.627355e-01,-1.116176e+00,1.091672,-1.194793,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,5.692100e+00
164,1.303041,1.264132,-3.940186e-01,6.520742e-01,-1.075355e-01,-4.807116e-01,-1.568994e+00,-1.116176e+00,0.155853,-0.130315,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,5.692100e+00
165,1.877984,0.265549,-3.940186e-01,-7.621647e-01,-1.075355e-01,9.789036e-01,-8.627355e-01,-3.092437e-01,0.214342,-0.130315,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,5.692100e+00
166,1.827464,0.454609,-3.940186e-01,-7.621647e-01,7.476275e-01,-1.210519e+00,-1.568994e+00,-1.519643e+00,-0.253568,0.743396,...,-0.077615,-7.761505e-02,-7.761505e-02,-1.352504e-01,-2.091650e-01,-1.100964e-01,-1.566521e-01,-1.352504e-01,-2.523772e-01,5.692100e+00
coefs,3.167782,0.618018,4.440632e+12,5.584104e+12,9.234797e+12,1.082101e+13,1.118181e+13,-1.957352e+13,2.116389,0.379517,...,-120.390639,-9.686418e+11,-9.686418e+11,-1.667599e+12,-2.516044e+12,-1.365734e+12,-1.919698e+12,-1.667599e+12,-2.978921e+12,-2.139694e+12

In [45]:
#this is the pre-transformed values of training set, you can see some features are entirely 0
pd.DataFrame(scaler.inverse_transform(X_train)).describe().T

,count,mean,std,min,25%,50%,75%,max
0,125.0,3802.976000,3289.550583,4.200000e+02,1.269000e+03,2.200000e+03,6.600000e+03,12075.0
1,125.0,859.528000,588.964422,1.750000e+02,4.000000e+02,7.000000e+02,1.150000e+03,2600.0
2,125.0,0.240000,0.601074,2.775558e-17,2.775558e-17,2.775558e-17,2.775558e-17,2.0
3,125.0,0.528000,0.724858,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.0
4,125.0,1.088000,1.136037,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,5.0
5,125.0,1.632000,1.411565,2.220446e-16,1.000000e+00,1.000000e+00,2.000000e+00,6.0
6,125.0,2.248000,1.473727,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,6.0
7,125.0,5.736000,2.521341,0.000000e+00,4.000000e+00,5.000000e+00,7.000000e+00,14.0
8,125.0,30.320000,17.429859,7.000000e+00,1.600000e+01,2.400000e+01,4.300000e+01,83.0
9,125.0,2.138724,0.971823,1.000000e+00,1.000000e+00,2.000000e+00,2.820789e+00,4.0
10,125.0,1.010132,0.737381,0.000000e+00,4.000000e-01,1.000000e+00,1.500000e+00,4.0
11,125.0,246.638410,295.219583,1.500000e+01,6.000000e+01,1.240000e+02,2.800000e+02,1500.0
12,125.0,104.036732,69.141576,1.300000e+01,4.500000e+01,8.400000e+01,1.748732e+02,300.0
13,125.0,105.675957,23.223847,5.600000e+01,9.000000e+01,1.100000e+02,1.151039e+02,163.0
14,125.0,59.013252,14.642146,2.200000e+01,5.100000e+01,5.800000e+01,6.600000e+01,95.0
15,125.0,151.348658,108.185657,2.000000e+01,5.600000e+01,1.200000e+02,2.100000e+02,500.0
16,125.0,50.082083,16.511211,2.000000e+01,3.900000e+01,4.900000e+01,5.791696e+01,89.0
17,125.0,110.703633,21.556049,5.600000e+01,1.000000e+02,1.130000e+02,1.200530e+02,170.0
18,125.0,39.912000,45.003408,0.000000e+00,0.000000e+00,3.000000e+01,6.600000e+01,180.0
19,125.0,0.912000,0.647775,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,2.0
20,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
21,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
22,125.0,0.056000,0.230847,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
23,125.0,0.024000,0.153665,-3.469447e-18,-3.469447e-18,-3.469447e-18,-3.469447e-18,1.0
24,125.0,0.024000,0.153665,-3.469447e-18,-3.469447e-18,-3.469447e-18,-3.469447e-18,1.0
25,125.0,0.048000,0.214626,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
26,125.0,0.024000,0.153665,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
27,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
28,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
29,125.0,0.032000,0.176708,-3.469447e-18,-3.469447e-18,-3.469447e-18,-3.469447e-18,1.0
30,125.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
31,125.0,0.016000,0.125980,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
32,125.0,0.080000,0.272385,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
33,125.0,0.056000,0.230847,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
34,125.0,0.016000,0.125980,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
35,125.0,0.016000,0.125980,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
36,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
37,125.0,0.072000,0.259528,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
38,125.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
39,125.0,0.032000,0.176708,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
40,125.0,0.096000,0.295777,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
41,125.0,0.016000,0.125980,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
42,125.0,0.024000,0.153665,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
43,125.0,0.024000,0.153665,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
44,125.0,0.064000,0.245738,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
45,125.0,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
46,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
47,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
48,125.0,0.024000,0.153665,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
49,125.0,0.056000,0.230847,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
50,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
51,125.0,0.016000,0.125980,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
52,125.0,0.008000,0.089443,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
53,125.0,0.080000,0.272385,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
54,125.0,0.032000,0.176708,-3.469447e-18,-3.469447e-18,-3.469447e-18,-3.469447e-18,1.0

In [46]:
pd.DataFrame(X_train).describe().T

,count,mean,std,min,25%,50%,75%,max
0,125.0,0.061716,1.019570e+00,-0.986811,-0.723670,-0.435114,0.928631,2.625565
1,125.0,0.041303,1.012271e+00,-1.135217,-0.748502,-0.232883,0.540546,3.032706
2,125.0,0.032799,1.068955e+00,-0.394019,-0.394019,-0.394019,-0.394019,3.162798
3,125.0,-0.015447,1.025123e+00,-0.762165,-0.762165,-0.762165,0.652074,2.066313
4,125.0,-0.032281,9.714970e-01,-0.962698,-0.962698,-0.107535,0.747628,3.313117
5,125.0,-0.019473,1.030171e+00,-1.210519,-0.480712,-0.480712,0.249096,3.168326
6,125.0,0.018676,1.040833e+00,-1.568994,-0.862735,-0.156477,0.549782,2.668559
7,125.0,-0.012292,1.017276e+00,-2.326576,-0.712710,-0.309244,0.497689,3.321954
8,125.0,0.057592,1.019449e+00,-1.306364,-0.779966,-0.312056,0.799228,3.138775
9,125.0,0.017353,1.034484e+00,-1.194793,-1.194793,-0.130315,0.743396,1.998640
10,125.0,0.038409,1.022540e+00,-1.362361,-0.807673,0.024359,0.717719,4.184519
11,125.0,0.010979,9.176968e-01,-0.709075,-0.569191,-0.370246,0.114684,3.907082
12,125.0,0.026647,1.015273e+00,-1.310134,-0.840247,-0.267572,1.066808,2.904165
13,125.0,0.001031,1.061374e+00,-2.269255,-0.715390,0.198648,0.431908,2.620849
14,125.0,-0.014436,1.024830e+00,-2.605059,-0.575297,-0.085355,0.474579,2.504341
15,125.0,0.061135,1.037763e+00,-1.198818,-0.853490,-0.239575,0.623743,3.405547
16,125.0,0.014806,1.046046e+00,-1.891004,-0.687284,-0.053748,0.511174,2.480398
17,125.0,-0.048024,1.036330e+00,-2.677959,-0.562612,0.062376,0.401457,2.802712
18,125.0,-0.039455,1.030698e+00,-0.953547,-0.953547,-0.266466,0.558030,3.168935
19,125.0,-0.006689,1.039697e+00,-1.470474,-1.470474,0.134553,0.134553,1.739581
20,125.0,0.026079,1.159331e+00,-0.077615,-0.077615,-0.077615,-0.077615,12.884099
21,125.0,0.026079,1.159331e+00,-0.077615,-0.077615,-0.077615,-0.077615,12.884099
22,125.0,0.037908,1.080929e+00,-0.224309,-0.224309,-0.224309,-0.224309,4.458139
23,125.0,-0.034855,9.016721e-01,-0.175682,-0.175682,-0.175682,-0.175682,5.692100
24,125.0,-0.034855,9.016721e-01,-0.175682,-0.175682,-0.175682,-0.175682,5.692100
25,125.0,0.064864,1.153217e+00,-0.193047,-0.193047,-0.193047,-0.193047,5.180090
26,125.0,0.045444,1.156934e+00,-0.135250,-0.135250,-0.135250,-0.135250,7.393691
27,125.0,-0.036552,8.222512e-01,-0.110096,-0.110096,-0.110096,-0.110096,9.082951
28,125.0,-0.075019,6.734090e-01,-0.135250,-0.135250,-0.135250,-0.135250,7.393691
29,125.0,0.012087,1.036885e+00,-0.175682,-0.175682,-0.175682,-0.175682,5.692100
30,125.0,-0.077615,1.393363e-17,-0.077615,-0.077615,-0.077615,-0.077615,-0.077615
31,125.0,-0.052008,8.239377e-01,-0.156652,-0.156652,-0.156652,-0.156652,6.383573
32,125.0,-0.034346,9.526473e-01,-0.314140,-0.314140,-0.314140,-0.314140,3.183290
33,125.0,0.037908,1.080929e+00,-0.224309,-0.224309,-0.224309,-0.224309,4.458139
34,125.0,0.036992,1.158140e+00,-0.110096,-0.110096,-0.110096,-0.110096,9.082951
35,125.0,-0.014787,9.484963e-01,-0.135250,-0.135250,-0.135250,-0.135250,7.393691
36,125.0,0.026079,1.159331e+00,-0.077615,-0.077615,-0.077615,-0.077615,12.884099
37,125.0,0.024720,1.046266e+00,-0.265543,-0.265543,-0.265543,-0.265543,3.765875
38,125.0,-0.077615,1.393363e-17,-0.077615,-0.077615,-0.077615,-0.077615,-0.077615
39,125.0,-0.021106,9.494776e-01,-0.193047,-0.193047,-0.193047,-0.193047,5.180090
40,125.0,-0.055970,9.314784e-01,-0.358299,-0.358299,-0.358299,-0.358299,2.790963
41,125.0,-0.014787,9.484963e-01,-0.135250,-0.135250,-0.135250,-0.135250,7.393691
42,125.0,0.000313,1.005003e+00,-0.156652,-0.156652,-0.156652,-0.156652,6.383573
43,125.0,0.045444,1.156934e+00,-0.135250,-0.135250,-0.135250,-0.135250,7.393691
44,125.0,0.017364,1.035711e+00,-0.252377,-0.252377,-0.252377,-0.252377,3.962323
45,125.0,-0.077615,1.393363e-17,-0.077615,-0.077615,-0.077615,-0.077615,-0.077615
46,125.0,0.026079,1.159331e+00,-0.077615,-0.077615,-0.077615,-0.077615,12.884099
47,125.0,0.026079,1.159331e+00,-0.077615,-0.077615,-0.077615,-0.077615,12.884099
48,125.0,0.045444,1.156934e+00,-0.135250,-0.135250,-0.135250,-0.135250,7.393691
49,125.0,0.070279,1.151945e+00,-0.209165,-0.209165,-0.209165,-0.209165,4.780914
50,125.0,-0.036552,8.222512e-01,-0.110096,-0.110096,-0.110096,-0.110096,9.082951
51,125.0,-0.052008,8.239377e-01,-0.156652,-0.156652,-0.156652,-0.156652,6.383573
52,125.0,-0.075019,6.734090e-01,-0.135250,-0.135250,-0.135250,-0.135250,7.393691
53,125.0,0.084799,1.148021e+00,-0.252377,-0.252377,-0.252377,-0.252377,3.962323
54,125.0,0.012087,1.036885e+00,-0.175682,-0.175682,-0.175682,-0.175682,5.692100

In [22]:
X

,summit_elev,vertical_drop,fastQuads,quad,triple,double,surface,total_chairs,Runs,TerrainParks,...,Rhode Island,South Dakota,Tennessee,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,2090,294,0,0,1,0,2,3,13.0,1.000000,...,0,0,0,0,0,0,0,0,0,0
1,11100,1800,1,2,3,1,0,7,65.0,2.000000,...,0,0,0,0,0,0,0,0,0,0
2,7800,600,0,0,1,3,1,5,10.0,2.000000,...,0,0,0,0,0,0,0,0,0,0
3,8012,750,0,0,1,5,2,8,52.0,2.000000,...,0,0,0,0,0,0,0,0,0,0
4,10090,2590,2,0,0,4,1,7,41.0,2.000000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,8000,640,0,0,0,1,1,2,28.0,1.000000,...,0,0,0,0,0,0,0,0,0,1
163,7428,810,0,0,1,1,1,3,48.0,1.000000,...,0,0,0,0,0,0,0,0,0,1
164,7808,1571,0,1,1,1,0,3,32.0,2.000000,...,0,0,0,0,0,0,0,0,0,1
165,9663,990,0,0,1,3,1,5,33.0,2.000000,...,0,0,0,0,0,0,0,0,0,1
166,9500,1100,0,0,2,0,0,2,25.0,2.820789,...,0,0,0,0,0,0,0,0,0,1

In [23]:
explained_variance_score(y_test, y_pred)

-6.1088502041064874e+22

**<font color='teal'> The intercept is the mean `AdultWeekend` price for all the resorts given the other characteristics. The addition or subtraction of each of the coefficient values in the regression are numeric adjustments applied to the intercept to provide a particular observation's value for the resulting `AdultWeekend` value. Also, because we took the time to scale our x values in the training data, we can compare each of the coeeficients for the features to determine the feature importances. Print the coefficient values from the linear model and sort in descending order to identify the top ten most important features.</font>** 


Hint: make sure to review the absolute value of the coefficients, because the adjustment may be positive or negative, but what we are looking for is the magnitude of impact on our response variable.

In [24]:
# You might want to make a pandas DataFrame displaying the coefficients for each state like so: 
# pd.DataFrame(abs(lm.coef_), X.columns, columns=['Coefficient'])

**<font color='teal'>You should see that the top ten important features are different states. However, the state is not something the managers at the Big Mountain Resort can do anything about. Given that we care more about actionable traits associated with ticket pricing, rebuild the model without the state features and compare the results. </font>**

Hint: Try to construct another model using exactly the steps we followed above.

#### Model 2

**<font color='teal'> When reviewing our new model coefficients, we see `summit_elev` is now in the number two spot. This is also difficult to change from a management prespective and highly correlated with `base_elev` and `vertical_drop`.  This time, rebuild the model without the state features and without the `summit_elev` and without `base_elev`and compare the results. </font>**

#### Model 3

## Identify the Final Model

**<font color='teal'> Review the model performances in the table below and choose the best model for proving insights to Big Mountain management about what features are driving ski resort lift ticket prices. Type your choice in the final markdown cell — you will discuss this selection more in the next step of the guided casptone. </font>**

| Model | Explained Variance| Mean Absolute Error|Features Dropped|
| --- | --- | --- | --- |
| Model 1. | 0. |  |-|
| Model 2. | 0.| |'state'|
| Model 3. | 0. | |'state','summit_elev','base_elev'|

Model Selection: